spring:
  application:
    name: thymeleaf
    
# DB 설정
  datasource:
    #driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@localhost:1521/xe
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
    username: springboot
    password: java1234

# MyBatis 설정
mybatis:
  type-aliases-package: com.test.thymeleaf.dto    
  mapper-locations: classpath:mapper/*.xml
        
server:
  port: 8090

  
  
  
  

