spring:
  application:
    name: oauth2

# oauth2 registration
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: XCbWlfjYbTWv1J3L2osJ
            client-secret: Vxnn8hfxAS
            redirect-uri: http://localhost:8090/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
        
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
    
server:
  port: 8090    

  
  
  
  
  
  
  
  
  
  