spring:
  application:
    name: oauth2

# oauth2 registration
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: XCbWlfjYbTWv1J3L2osJ
            client-secret: Vxnn8hfxAS
            redirect-uri: http://localhost:8090/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            
          google:
            client-name: google
            client-id: 120943296032-hekcnd0tlh5388reb77a6qdn02glfo5n.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8090/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
        
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response       

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: springboot
    password: java1234
    
  # JPA 설정
  jpa:
    database: oracle
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true    

server:
  port: 8090    

  
  
  

  
  
  
  
  
  